application: inlaid-woods-135304
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: htdocs/index.html
  upload: /

- url: /
  static_dir: htdocs

- url: /.*
  script: main.app
